import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";

const LinkStyles =
  "text-white text-6xl font-mono font-thin mx-4 py-2 group-hover:opacity-30 hover:!opacity-100 z-10 ease-in duration-200";

const Home: NextPage = () => {
  const [activeIndex, setActiveIndex] = useState(-1);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative flex min-h-screen flex-col items-start justify-center overflow-hidden bg-gradient-to-r from-[#302b63] to-[#24243e] sm:items-center">
        <div className="group peer relative z-20 ml-2 flex flex-col items-stretch justify-center sm:ml-0 sm:mr-[30%]">
          <Link
            href="/"
            className={LinkStyles}
            data-active-index={0}
            onMouseOver={() => setActiveIndex(0)}
          >
            Home
          </Link>
          <Link
            href="/"
            className={LinkStyles}
            onMouseOver={() => setActiveIndex(1)}
          >
            About Me
          </Link>
          <Link
            href="/"
            className={LinkStyles}
            onMouseOver={() => setActiveIndex(2)}
          >
            Blog
          </Link>
          <Link
            href="/"
            className={LinkStyles}
            onMouseOver={() => setActiveIndex(3)}
          >
            Projects
          </Link>
        </div>
        <Image
          alt="pattern"
          src=""
          fill
          className="absolute z-10 opacity-10 duration-300 ease-in peer-hover:opacity-5"
          style={{
            backgroundPosition: `0% ${(activeIndex + 1) * -50}%`,
            backgroundImage: "url('/homepage-pattern.svg')",
            objectFit: "contain",
            height: "1200px",
          }}
        />
        <Image
          alt="keyboard"
          src=""
          fill
          className="absolute z-0 opacity-10 duration-300 ease-out peer-hover:opacity-5 scale-105 peer-hover:scale-100"
          style={{
            backgroundPosition: `center ${40 + (activeIndex + 1) * 10}%`,
            backgroundImage: "url('/homepage-bg.jpg')",
            backgroundSize: "auto 110vmax",
            backgroundRepeat: "no-repeat",
          }}
        />
      </main>
    </>
  );
};

export default Home;
