import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";

const LinkStyles =
  "text-white text-6xl font-serif font-thin mx-4 py-2 group-hover:opacity-30 hover:!opacity-100 z-10 ease-in duration-200";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-start justify-center bg-gradient-to-r from-[#302b63] to-[#24243e]">
        <div className="ml-8 group peer z-10 flex flex-col items-stretch justify-center">
          <Link href="/" className={LinkStyles}>
            Home
          </Link>
          <Link href="/" className={LinkStyles}>
            About Me
          </Link>
          <Link href="/" className={LinkStyles}>
            Projects
          </Link>
          <Link href="/" className={LinkStyles}>
            Coursework
          </Link>
        </div>
        <div
          id="menu-background-pattern"
          className="absolute z-0 h-screen w-screen bg-pattern bg-pattern-size bg-left-top duration-300 ease-in peer-hover:opacity-50"
        ></div>
      </main>
    </>
  );
};

export default Home;
